### ISSUE TITLE
스토리 디자인 반영 및 에러 수정

### ISSUE THREAD

**Issue by SJ-Kwak** [sdp-tech/SASM_Mobile#161]
## Description
- 스토리 디자인 반영 및 에러 수정

## To-Do
- [x] high-fi 디자인 반영
- [x] filter 배열 수정
- [x] 로그인 체크
- [x] 사진 업로드 에러
- [x] 작성 중 뒤로 가기 방지
