### ISSUE TITLE
알림 기능 구현

### ISSUE THREAD

**Issue by SJ-Kwak** [sdp-tech/SASM_Mobile#255]
## Description
- Firebase Messaging 활용해서 알림 기능 구현

## To-Do
- [x] Firebase Messaging 연결
- [x] 알림 허용 기능 설정
- [ ] push notifications 라이브러리 연결
