### ISSUE TITLE
MyPick 스크린 구현 및 세부 기능 구현

### ISSUE THREAD

**Issue by SeoJimin1234** [sdp-tech/SASM_Mobile#89]
## Description
- MyPlace, MyStory의 스크린, 세부기능 구현
## To-Do
- [x] MyPlace 화면 style 적용
- [x] MyStory 화면 style 적용
- [x] category 아이콘 띄우기(image require 사용)
